<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admission</name>
   <tag></tag>
   <elementGuidId>4a8cf5eb-fd57-49da-9951-402c8fa40565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primary-menu > li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-558 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='primary-menu']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#primary-menu >> internal:role=link[name=&quot;Admission&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49d12842-cdcf-4317-a5c1-7ece31e6f792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://tkscas.com/college-admission/</value>
      <webElementGuid>8f130947-b8e7-4315-b1e5-b27fab3b9b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admission</value>
      <webElementGuid>d5fe49be-d393-493b-b2e2-99c3190183d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-558&quot;]/a[1]</value>
      <webElementGuid>cd8397e8-8d28-4e02-b27e-321a22775778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='primary-menu']/li[4]/a</value>
      <webElementGuid>67b822ee-5b52-425a-952c-a2bf4d062cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Admission')])[4]</value>
      <webElementGuid>6d34e54c-3dc5-49e0-8fd8-e98621cbb26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumni'])[4]/following::a[1]</value>
      <webElementGuid>eed31ee3-72c4-4e14-862d-f01a202f3333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam'])[4]/following::a[2]</value>
      <webElementGuid>10faf44b-72f7-4d1f-bb47-6fdf823d3518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laboratory'])[2]/preceding::a[2]</value>
      <webElementGuid>f1e8a4a5-3e1a-4b74-b36e-9dd819a7bfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[2]/preceding::a[3]</value>
      <webElementGuid>abf0c6f4-8891-47fe-a3f0-d9de564e9a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://tkscas.com/college-admission/')])[2]</value>
      <webElementGuid>22a88078-998f-4183-bab1-720ca23407e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/ul/li[4]/a</value>
      <webElementGuid>467fcbc2-a3f5-48f7-87ac-0d4d69b8077c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://tkscas.com/college-admission/' and (text() = 'Admission' or . = 'Admission')]</value>
      <webElementGuid>569b9ef5-79e3-440b-9451-d7abc3648365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
