<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_General</name>
   <tag></tag>
   <elementGuidId>dac8cafe-ac1b-46b3-a07a-4d8a4fe941cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primary-menu > li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-has-children.menu-item-701 > ul.sub-menu > li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-700 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='primary-menu']/li[9]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#primary-menu >> internal:role=link[name=&quot;General&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d87de89e-86a6-4e14-995b-44d17422ec73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://tkscas.com/general/</value>
      <webElementGuid>53ef7772-b0ff-4a65-a026-ac5dd59597c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General</value>
      <webElementGuid>9f4ec773-c158-428f-9fd6-31047c8ac2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-701&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-700&quot;]/a[1]</value>
      <webElementGuid>9011905f-92dd-49fe-93aa-443a4792cf8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='primary-menu']/li[9]/ul/li/a</value>
      <webElementGuid>30453dc6-7b20-4a38-a151-f0221e75ab97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'General')])[2]</value>
      <webElementGuid>106bf00b-88e9-4c80-865a-b089f75e3589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[2]/following::a[2]</value>
      <webElementGuid>0cca7d8b-1360-4b6d-ab2e-f45e37798ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Activities'])[2]/following::a[3]</value>
      <webElementGuid>b3a99f5b-c285-44da-8b99-ed552868ccbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[2]/preceding::a[1]</value>
      <webElementGuid>922c5b54-f9bd-40cf-92fe-0e13d562e6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SC/ST'])[2]/preceding::a[2]</value>
      <webElementGuid>0e582e46-e347-46f8-912d-15e48c0bb122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://tkscas.com/general/')])[2]</value>
      <webElementGuid>d7de23e9-4704-442a-aac7-fb9e97a51b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/ul/li[9]/ul/li/a</value>
      <webElementGuid>b2d182f5-2afe-4d03-836c-cdee0b4a329d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://tkscas.com/general/' and (text() = 'General' or . = 'General')]</value>
      <webElementGuid>f9a44054-78e0-4630-b0e1-a1e91213f737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
