<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NIRF</name>
   <tag></tag>
   <elementGuidId>7cb63731-ac50-47f6-9631-a2f2fd8d85c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primary-menu > li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-1083 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='primary-menu']/li[11]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#primary-menu >> internal:role=link[name=&quot;NIRF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96fa1b72-531a-4f91-894b-3d8038bf0743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://tkscas.com/nirf-details/</value>
      <webElementGuid>9fbc2889-24b6-440f-8268-5bbb6bb226ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIRF</value>
      <webElementGuid>c699afb9-29f1-4783-9785-0b7ba9293557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-1083&quot;]/a[1]</value>
      <webElementGuid>ffbaae3c-908b-4216-a458-9ea19db665fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='primary-menu']/li[11]/a</value>
      <webElementGuid>7804387a-c1a5-4dca-bfc9-d4487031d9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'NIRF')])[2]</value>
      <webElementGuid>c75aaeb9-39db-4a3e-84fe-4c2ca1a6bc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/following::a[1]</value>
      <webElementGuid>4914cf91-4706-410d-977d-2229497c9d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SC/ST'])[2]/following::a[2]</value>
      <webElementGuid>68fcaa9d-bfc8-4888-a655-847600d1919c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[3]/preceding::a[1]</value>
      <webElementGuid>f39350ce-204a-430a-bb74-778a8dbc0a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/preceding::a[1]</value>
      <webElementGuid>343a9d50-8d83-4f08-b481-ea19bb7ce081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://tkscas.com/nirf-details/')])[2]</value>
      <webElementGuid>1b52c819-b941-4adf-a4a7-9cd432246351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/ul/li[11]/a</value>
      <webElementGuid>e38b0004-a403-42fd-94a7-a7bafef892e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://tkscas.com/nirf-details/' and (text() = 'NIRF' or . = 'NIRF')]</value>
      <webElementGuid>17d8d3ce-f727-4aad-b83a-ab9751fb022a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
