<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>72d1d521-42b3-46a4-8a85-cf70d75e3bfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.section-head > div > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aboutus']/div/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.section-head > div > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e9bed879-a9d7-47f3-a1ea-a222242be615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>QS_World_University_Rankings_2025.jpeg</value>
      <webElementGuid>33525e0b-6b8f-4289-ad67-40809860b812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>3dd462d0-0c51-4fe2-8e4b-21ff6c1fa984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>f89f6053-05dd-4c04-8c6b-edf2b33cec3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1cae1ccf-e1ff-4dda-ba16-75c4bb41b199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bg&quot;)/div[@id=&quot;aboutus&quot;]/div[@id=&quot;aboutus&quot;]/div[@class=&quot;row service-area-one&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head&quot;]/div[1]/a[1]/img[1]</value>
      <webElementGuid>333d7586-2eb8-4839-8522-9dca89bf491c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aboutus']/div/div[2]/div/div/a/img</value>
      <webElementGuid>505cb41d-c91e-4688-b51f-821964c92ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>a33159d0-7a50-4262-95c6-f8961d81a6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'QS_World_University_Rankings_2025.jpeg']</value>
      <webElementGuid>856d86bd-e9da-470f-8f8c-0b5e573fa843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
